version: '2'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'forms'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_DB=forms'
    volumes:
      - ./docker-compose:/docker-entrypoint-initdb.d